config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic.base import TemplateView, RedirectView
from django_tequila.urls import urlpatterns as django_tequila_urlpatterns
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required, user_passes_test
from decorator_include import decorator_include
from exoset.ontology.models import Ontology


def only_user(group_name):
    def check(user):
        user_groups = user.groups.values_list('name', flat=True)
        if user.is_authenticated and group_name in user_groups:
            return True
        raise PermissionDenied
    return user_passes_test(check)


def root_ontology():
    return Ontology.get_root_nodes().values_list('name', flat=True)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n'), name='set_language'),
    path("", RedirectView.as_view(pattern_name='document:exercises-list-no-filter', permanent=False)),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html",
                                       extra_context=dict(list_parent_ontology=root_ontology())), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("users/", include("exoset.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("resources/", include("exoset.document.urls", namespace="document")),
    path("admin_github/", decorator_include([login_required, only_user('github_user')],
         include("exoset.githubadmin.urls", namespace="githubadmin"))),
    path("graphapi/", include("exoset.graphapi.urls", namespace="graphapi")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += django_tequila_urlpatterns

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

exoset/githubadmin/urls.py
from django.urls import include, path
from .views import list_pull_request, MetadataFormView, PullRequestDetail, merge_pull_request, \
    prerequisites_autocomplete, ResourceListAdmin, load_ontology_level1, publish_resource, concepts_autocomplete, \
    change_flag_option, AdminGithub
app_name = "githubadmin"

urlpatterns = [
    path('<str:github_repo>/', include([
        path("list_pull_request/", list_pull_request, name='pull_request_list'),
    #    path('task_list/<str:sort>/', ResourceListAdmin.as_view(), name='task_sort'),
        path("list_resources_files", ResourceListAdmin.as_view(), name='list_resources_files'),
        path("merge_pull/<int:pull_request_id>", merge_pull_request, name='pull_request_merge'),
        path("pull_request/<int:id>", PullRequestDetail.as_view(), name='pull_request_detail'),
        path("metadata_creation/<id>/<str:folder_name>", MetadataFormView.as_view(), name='metadata_creation'),
        path('ajax/resource_visible/', publish_resource, name="publish_resource"),
        path("change_flag", change_flag_option, name='change_flag_resource'),
    ])),
    path('list_repositories', AdminGithub.as_view(), name='list_repositories'),
    #path("list_pull_request/", list_pull_request, name='pull_request_list'),
    #path("metadata_creation/<id>/<str:folder_name>", MetadataFormView.as_view(), name='metadata_creation'),
    #path("pull_request/<int:id>", PullRequestDetail.as_view(), name='pull_request_detail'),
    #path("merge_pull/<int:pull_request_id>", merge_pull_request, name='pull_request_merge'),
    path("autocomplete_prerequisites", prerequisites_autocomplete, name='prerequisite_autocomplete'),
    path("autocomplete_concepts", concepts_autocomplete, name='concept_autocomplete'),
    #path("list_resources_files", ResourceListAdmin.as_view(), name='list_resources_files'),
    path('ajax/load-ontology_children/', load_ontology_level1, name='ajax_load_ontology'),
    #path('ajax/resource_visible/', publish_resource, name="publish_resource"),
    #path('task_list/<str:sort>/', ResourceListAdmin.as_view(), name='task_sort'),
    #path("change_flag", change_flag_option, name='change_flag_resource'),

    # Your stuff: custom urls includes go here
]

exoset/githubadmin/models.py
from django.db import models

# Create your models here.


class GitHubRepository(models.Model):
    repository_name = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    token = models.CharField(max_length=255)
    official = models.BooleanField(default=False)

exoset/githubadmin/forms.py
from django import forms
from exoset.tag.models import TagProblemType, TagLevel, QuestionType, TagLevelResource, TagProblemTypeResource, \
    QuestionTypeResource, TagConcept
from exoset.ontology.models import Ontology, DocumentCategory
from exoset.document.models import LANGUAGES_CHOICES, Resource
from exoset.prerequisite.models import AssignPrerequisiteResource
from django.utils.translation import gettext_lazy as _
from exoset.accademic.models import Sector, Course

VISIBLE_CHOICES = [(1, _('Yes')), (0, _('No'))]


def query_set_root_children():
    children = []
    roots = Ontology.get_root_nodes()
    for x in roots:
        children += x.get_children()
    return children


def query_set_parent_children():
    children = []
    roots = query_set_root_children()
    for x in roots:
        children += x.get_children()
    return children


choices_root = [(x.pk, _(x.name)) for x in Ontology.get_root_nodes()]
choices_root.insert(0, (None, '-----'))

choices_parent = [(x.pk, _(x.name)) for x in query_set_root_children()]
choices_parent.insert(0, (None, '-----'))

choices_children = [(x.pk, _(x.name)) for x in query_set_parent_children()]
choices_children.insert(0, (None, '-----'))

choices_cour = [(x.pk, _(x.name)) for x in Sector.objects.all()]
choices_cour.insert(0, (None, '-----'))


class MetadataForm(forms.Form):
    language = forms.ChoiceField(
        required=True,
        label=_('Language'),
        widget=forms.Select,
        choices=LANGUAGES_CHOICES)
    title = forms.CharField(required=True, label=_('Title*'), max_length=255)
    authors = forms.CharField(required=True, label=_('Collection*'), max_length=255)
    difficulty_level = forms.ChoiceField(
        required=True,
        label=_('Difficulty level*'),
        widget=forms.Select,
        choices=((x.pk, _(x.label)) for x in TagLevel.objects.all())
    )
    question_type = forms.ChoiceField(
        required=False,
        label=_('Type of question'),
        widget=forms.Select,
        choices=((x.pk, _(x.label)) for x in QuestionType.objects.all())
    )
    class_type = forms.ChoiceField(
        required=False,
        label=_('Class'),
        widget=forms.Select,
        choices=choices_cour
    )
    family_problem = forms.CharField(required=False, label=_('Family problem'), max_length=255)
    root_ontology0 = forms.ChoiceField(required=True, label=_('Ontology*'), choices=choices_root,
                                       widget=forms.Select(attrs={'class': 'root_ontology_input',
                                                                  'data-line': '0'}))
    parent_ontology0 = forms.ChoiceField(required=True, label='', choices=choices_parent,
                                         widget=forms.Select(attrs={'class': 'parent_ontology_input',
                                                                    'data-line': '0'}))
    ontology0 = forms.ChoiceField(required=True, label='', choices=choices_children,
                                  widget=forms.Select(attrs={'class': 'ontology_input',
                                                             'data-line': '0'}))
    root_ontology1 = forms.ChoiceField(required=False, label=_('Extra ontology'), choices=choices_root,
                                       widget=forms.Select(attrs={'class': 'root_ontology_input',
                                                                  'data-line': '1'}))
    parent_ontology1 = forms.ChoiceField(required=False, label='', choices=choices_parent,
                                         widget=forms.Select(attrs={'class': 'parent_ontology_input',
                                                                    'data-line': '1'}))
    ontology1 = forms.ChoiceField(required=False, label='', choices=choices_children,
                                  widget=forms.Select(attrs={'class': 'ontology_input',
                                                             'data-line': '1'}))
    concept0 = forms.CharField(required=False, label=_("Concept"), max_length=255, widget=forms.TextInput(
        attrs={'url': '/admin_github/autocomplete_concepts',
               'id': 'concept0',
               'class': 'concepts',
               }))
    concept1 = forms.CharField(required=False, label=_("Extra concept"), widget=forms.TextInput(
        attrs={'url': '/admin_github/autocomplete_concepts',
               'id': 'concept1',
               'class': 'concepts',
               }))
    concept2 = forms.CharField(required=False, label=_("Extra concept"), max_length=255, widget=forms.TextInput(
        attrs={'url': '/admin_github/autocomplete_concepts',
               'id': 'concept2',
               'class': 'concepts',
               }))
    concept3 = forms.CharField(required=False, label=_("Extra concept"), max_length=255, widget=forms.TextInput(
        attrs={'url': '/admin_github/autocomplete_concepts',
               'id': 'concept3',
               'class': 'concepts',
               }))
    concept4 = forms.CharField(required=False, label=_("Extra concept"), max_length=255, widget=forms.TextInput(
        attrs={'url': '/admin_github/autocomplete_concepts',
               'id': 'concept4',
               'class': 'concepts',
               }))
    prerequisite0 = forms.CharField(required=False, label=_("Prerequisite"), widget=forms.TextInput(
        attrs={
            'url': '/admin_github/autocomplete_concepts',
            'id': 'prerequisite0',
            'class': 'prerequisites',
        }))
    prerequisite1 = forms.CharField(required=False, label=_("Extra prerequisite"), widget=forms.TextInput(
        attrs={
            'url': '/admin_github/autocomplete_concepts',
            'id': 'prerequisite1',
            'class': 'prerequisites',
        }))
    prerequisite2 = forms.CharField(required=False, label=_("Extra prerequisite"), widget=forms.TextInput(
        attrs={
            'url': '/admin_github/autocomplete_concepts',
            'id': 'prerequisite2',
            'class': 'prerequisites',
        }))
    prerequisite3 = forms.CharField(required=False, label=_("Extra prerequisite"), widget=forms.TextInput(
        attrs={
            'url': '/admin_github/autocomplete_concepts',
            'id': 'prerequisite3',
            'class': 'prerequisites',
        }))
    prerequisite4 = forms.CharField(required=False, label=_("Extra prerequisite"), widget=forms.TextInput(
        attrs={
            'url': '/admin_github/autocomplete_concepts',
            'id': 'prerequisite4',
            'class': 'prerequisites',
        }))

    def __init__(self, *args, **kwargs):
        """
        fill the form with existing data in database if existing
        """
        resource_id = kwargs.pop('id')
        folder_name = kwargs.pop('exercise_folder_name')
        super(MetadataForm, self).__init__(*args, **kwargs)
        if resource_id != 'None':
            # get data from database
            resource = Resource.objects.get(id=int(resource_id))
            title_exercise = resource.title
            level = TagLevelResource.objects.get(resource_id=resource.id).tag_level.id
            try:
                question = QuestionTypeResource.objects.get(resource_id=resource.pk).question_type.pk
            except QuestionTypeResource.DoesNotExist:
                question = ""
            try:
                tag_problem_type = TagProblemTypeResource.objects.get(resource_id=resource.pk).tag_problem_type
            except TagProblemTypeResource.DoesNotExist:
                tag_problem_type = None
            concepts = TagConcept.objects.filter(resource_id=resource.pk)
            try:
                prerequisites = AssignPrerequisiteResource.objects.get(resource_id=resource.pk).prerequisite.all()
            except AssignPrerequisiteResource.DoesNotExist:
                prerequisites = None
            try:
                ontologies = DocumentCategory.objects.filter(resource_id=resource.pk)
            except DocumentCategory.DoesNotExist:
                ontologies = None
            try:
                sector = Course.objects.get(resource=resource).sector.id
            except Course.DoesNotExist:
                sector = None
            self.fields['title'].initial = title_exercise
            self.fields['authors'].initial = resource.author
            self.fields['language'].initial = resource.language
            self.fields['difficulty_level'].initial = level
            self.fields['question_type'].initial = question
            self.fields['family_problem'].initial = tag_problem_type
            self.fields['class_type'].initial = sector
            if concepts:
                i = 0
                for concept in concepts:
                    self.fields['concept' + str(i)].initial = concept.label
                    i += 1
            if prerequisites:
                y = 0
                for prerequisite in prerequisites:
                    self.fields['prerequisite' + str(y)].initial = prerequisite.label
                    y += 1
            if ontologies:
                index_ontologies = 0
                for ontology in ontologies:
                    self.fields['root_ontology' + str(index_ontologies)].initial = ontology.category.get_root().id
                    self.fields['parent_ontology' + str(index_ontologies)].initial = ontology.category.get_parent().id
                    self.fields['ontology' + str(index_ontologies)].initial = ontology.category.id
                    index_ontologies += 1
                    if index_ontologies >= 2:
                        break


class ResourceForm(forms.Form):
    visible = forms.ChoiceField(choices=VISIBLE_CHOICES, widget=forms.RadioSelect)


class FlagForm(forms.Form):
    flag_resource = forms.ChoiceField(choices=Resource.FLAG_CHOICES)

exoset/githubadmin/templates/children_dropdown_list_options.html
<option value="">---------</option>
{% for ontology in childrens %}
<option value="{{ ontology.pk }}">{{ ontology.name }}</option>
{% endfor %}

exoset/githubadmin/templates/error_merge.html
{% extends "index.html" %}
{% load static i18n %}

{% block title %}
  <title>Exoset - {% trans "Administration GitHub" %} </title>
{% endblock %}
{% block content %}

  <h2>{% trans "Something went wrong with the merge, verify on GitHub or contact the administrator"%}</h2>
  <h4><a href="{% url 'githubadmin:pull_request_list' %}">{% trans "Go back to the list" %}</a></h4>
{% endblock %}

exoset/githubadmin/templates/metadata_form.html
{% extends "index.html" %}
{% load static i18n group_extra %}

{% block title %}
  <title>Exoset - {% trans "Create metadata file" %} </title>
{% endblock %}



{% block content %}
  <header role="banner" class="header header-light">
    <script src="https://cdn.polyfill.io/v2/polyfill.js?features=String.prototype.includes,Array.prototype.includes,Array.prototype.find,CustomEvent"></script>


  <div class="header-light-content">
    <a class="logo" href="https://www.epfl.ch">
      <img src="{% static '/svg/epfl-logo.svg' %}" alt="Logo EPFL, École polytechnique fédérale de Lausanne" class="img-fluid">
    </a>
    <p class="site-title">
      <a href="https://exoset.epfl.ch">ExoSet</a>
    </p>

    <ul aria-hidden="true" class="nav-header d-none d-xl-flex" >
      <li>
       <a class="nav-item" href="{% url 'githubadmin:list_resources_files' github_repo %}">{% trans "Exercises list in repository" %} <b>{{ github_repo }}</b></a>
      </li>
      <li>
        <a href="{% url  'githubadmin:pull_request_list' github_repo %}">{% trans "Pull requests list" %}</a>
      </li>
    </ul>



    <div class="dropdown dropright search d-none d-xl-block">
      <a class="dropdown-toggle" href="#" data-toggle="dropdown">
        <svg class="icon" aria-hidden="true">
          <use xlink:href="#icon-search"></use>
        </svg>
      </a>

    </div>

    <nav class="nav-lang nav-lang-short ml-auto">

        <form id="select-language" action="{% url 'set_language' %}" method="post">{% csrf_token %}
          <input name="next" type="hidden" value="{{ request.get_full_path|html_decode}}" />
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <ul>
              <li>
                <button {% if LANGUAGE_CODE == 'fr' %} class="language_button active" {% else %} class="language_button gray-color" {% endif %} name="language" value="fr" aria-label="Français"> <span>FR</span> </button>
              </li>

              <li>
                <button {% if LANGUAGE_CODE == 'en' %} class="language_button active" {% else %} class="language_button gray-color" {% endif %} name="language" value="en" aria-label="English"><span> EN</span> </button>
              </li>
            </ul>
        </form>

    </nav>
    <div class="btn btn-secondary nav-toggle-mobile d-xl-none">
      <span class="label">Menu</span>
      <div class="hamburger">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
</header>

  <!--- END HEADER ----->
  <!------- MAIN CONTAINER ----------------->
  <div class="main-container">
<div class="nav-toggle-layout nav-aside-layout">
  <div class="overlay"></div>

  <nav id="main-navigation" class="nav-main" role="navigation">
    <div class="nav-wrapper">
      <div class="nav-container current-menu-parent">
        <ul class="nav-menu">
          <!--<li class="menu-item-has-children">Categories</li>-->
          <li><a href="{% url 'githubadmin:list_resources_files' github_repo %}">{% trans "Exercises list for the repository" %} "{{ github_repo }}"</a></li>
          <li><a href="{% url  'githubadmin:pull_request_list' github_repo %}">{% trans "Pull requests list" %}</a></li>

        </ul>
      </div>
    </div>
  </nav>
  <!-----------END ASIDE NAVIGATION  ----------------------->

<div class="w-100 pb-5">
  <!----METADATA FORM -->
    <div class="card-body" style="margin-left: 27px!important;">
<form method="post"  id="metadataForm" data-ontology-url="{% url 'githubadmin:ajax_load_ontology' %}" novalidate>
    {% csrf_token %}

<table class="table table_character">
 <tr>
   <td><label for="id_title">{% trans 'Title:*' %}</label><br>
    {{ form.title }}
   </td>
   <td><label for="id_language">{% trans 'Language:' %}</label><br>

     {{ form.language}}

   </td>

   <td rowspan="13" colspan="3">
     <div class="card-body" >
       <div class="chart-area" style="height: 800px;width: 750px">
        <iframe id="exercise_pdf" src="{% static 'pdfjs-2.0/web/viewer.html' %}?file={{ file_location}}" style="border: none;"  width="100%" height="100%">
          {% trans "This browser does not support PDFs. Please download the PDF to view it:" %}
        </iframe>
       </div>
     </div>
   </td>
 </tr>
  <tr>
 <td><label for="id_authors">{% trans 'Collection:' %}*</label><br>
    {{ form.authors }}</td>
    <td><label for="id_difficulty_level">{% trans 'Difficulty level:' %}*</label><br>
    {{ form.difficulty_level }}</td>
 </tr>
  <tr>
    <td><label for="id_family_problem">{% trans 'Family problem' %}</label><br>
    {{ form.family_problem }}</td>
    <td ><label for="id_class_type">{% trans 'Class' %}</label><br>
    {{ form.class_type }}</td>
  </tr>
  <tr>

    <td colspan="2"><label for="id_question_type">{% trans 'Type of question:' %}*</label><br>
    {{ form.question_type }}</td>
  </tr>

  <tr class="table_group">
    <td><label for="id_root_ontology0">{% trans 'Ontology' %}*</label><br>
    {{ form.root_ontology0 }}</td>
    <td><br>{{ form.parent_ontology0 }}
   {{ form.ontology0 }}</td>
  </tr>

  <tr class="table_group">
    <td><label for="id_root_ontology1">{% trans 'Extra ontology' %}</label><br>
    {{ form.root_ontology1 }}</td>
    <td><br>{{ form.parent_ontology1 }}
    {{ form.ontology1 }}</td>
  </tr>

  <tr>
    <td><label for="id_concept0">{% trans "Concept" %}</label><br>
      {{ form.concept0 }}
    </td>
    <td><label for="id_concept1">{% trans "Extra concept" %}</label><br>
    {{ form.concept1 }}
    </td>

  </tr>
  <tr>
    <td><label for="id_concept2">{% trans "Extra concept" %}</label><br>
    {{ form.concept2 }}
    </td>
    <td><label for="id_concept3">{% trans "Extra concept" %}</label><br>
    {{ form.concept3 }}
    </td>

  </tr>
<tr>
  <td colspan="2"><label for="id_concept4">{% trans "Extra concept" %}</label><br>
    {{ form.concept4 }}
    </td>
</tr>
  <tr class="table_group">
    <td><label for="id_prerequisite0">{% trans "Prerequisite" %}</label><br>
    {{ form.prerequisite0 }}
    </td>
    <td><label for="id_prerequisite1">{% trans "Extra prerequisite" %}</label><br>
    {{ form.prerequisite1 }}
    </td>

  </tr>
  <tr class="table_group">
    <td><label for="id_prerequisite2">{% trans "Extra prerequisite" %}</label><br>
    {{ form.prerequisite2 }}
    </td>
    <td><label for="id_prerequisite3">{% trans "Extra prerequisite" %}</label><br>
    {{ form.prerequisite3 }}
    </td>

  </tr>
  <tr class="table_group">
    <td colspan="2"><label for="id_prerequisite4">{% trans "Extra prerequisite" %}</label><br>
    {{ form.prerequisite4 }}
    </td>
  </tr>


<tr>
<td>
    <input type="submit" value="Save">
</td>
</tr>

</table>
</form>
<!----END METADATA FORM----->
    </div>
</div>

<script>
  $(function () {

    let url = $("input.prerequisites").attr("url");
    console.log("url is " + url)
    var availableTags = [];
    $.ajax({
        method: 'GET',
        url: url,
        data: {},
        success: function (result) {
            $.each(result["tagsconcepts"], function (a, b) {
                availableTags.push(b)
            });
        },
        error: function(response){
            console.log(response)
        }
    });

    function split( val ) {
      return val.split( /,\s*/ );
    }

    function extractLast( term ) {
      return split( term ).pop();
    }

    $( ".prerequisites").bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).data( "ui-autocomplete" ).menu.active ) {
          event.preventDefault();
        }
      })
      .autocomplete({
        minLength: 0,
        source: function( request, response ) {
          response( $.ui.autocomplete.filter(
            availableTags, extractLast( request.term ) ) );
        },
        focus: function() {
          return false;
        },
        select: function( event, ui ) {
          var terms = split( this.value );
          terms.pop();
          terms.push( ui.item.value );
          terms.push( "" );
          if (terms.length > 2) {
            terms.shift()
          }

          this.value = terms.join( ", " );//.replace(", ", "");
          return false;
        },

      });
  });

    //$("#id_root_ontology0").change(function () {
    $(".root_ontology_input").change(function () {
      var url = $('#metadataForm').attr('data-ontology-url');
      var parentId = $(this).val();  // get the selected country ID from the HTML input
      var line = $(this).attr('data-line')
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request
        data: {
          'root': parentId// add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_parent_ontology"+line).html(data);
          //$("#id_ontology"+line).html(data['nephew']);
        }
      });

    });
    $(".parent_ontology_input").change(function () {
      var url = $('#metadataForm').attr('data-ontology-url');
      var parentId = $(this).val();  // get the selected country ID from the HTML input
      var line = $(this).attr('data-line')
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'root': parentId      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_ontology"+line).html(data);

        }
      });

    });

    /* GRAPHSEARCH */
  $(function ()
  {
    var lastEntry = ""
    $(".concepts").keyup(function () {
      var this_concept = $(this).attr('id')
      if ($(this).val() != lastEntry) {
        let url = $("input.concepts").attr("url");
        console.log("url is " + url)
        console.log("t is " + $(this).val())

        $.ajax({
          method: 'GET',
          url: url,
          data: {'term': $(this).val()},
          success: function (result) {
            var availableConcept = [];
            $.each(result["tagsconcepts"], function (a, b) {
              availableConcept.push(b)

            });
        $( "#"+ this_concept ).bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).data( "ui-autocomplete" ).menu.active ) {
          event.preventDefault();
        }
      })
        .autocomplete({
      source: availableConcept
    });
          },
          error: function (response) {
            console.log(response)
          }
        });
        lastEntry = $(this).val();



      }
    });

  })

  $(function ()
  {
    var lastEntry = ""
    $(".prerequisites").keyup(function () {
      var this_concept = $(this).attr('id')
      if ($(this).val() != lastEntry) {
        let url = $("input.prerequisites").attr("url");
        console.log("url is " + url)
        console.log("t is " + $(this).val())

        $.ajax({
          method: 'GET',
          url: url,
          data: {'term': $(this).val()},
          success: function (result) {
            var availableConcept = [];
            $.each(result["tagsconcepts"], function (a, b) {
              availableConcept.push(b)

            });
        $( "#"+ this_concept ).bind( "keydown", function( event ) {
        if ( event.keyCode === $.ui.keyCode.TAB &&
            $( this ).data( "ui-autocomplete" ).menu.active ) {
          event.preventDefault();
        }
      })
        .autocomplete({
      source: availableConcept
    });
          },
          error: function (response) {
            console.log(response)
          }
        });
        lastEntry = $(this).val();



      }
    });

  })

  </script>



{% endblock %}