config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic.base import TemplateView, RedirectView
from django_tequila.urls import urlpatterns as django_tequila_urlpatterns
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required, user_passes_test
from decorator_include import decorator_include
from exoset.ontology.models import Ontology


def only_user(group_name):
    def check(user):
        user_groups = user.groups.values_list('name', flat=True)
        if user.is_authenticated and group_name in user_groups:
            return True
        raise PermissionDenied
    return user_passes_test(check)


def root_ontology():
    return Ontology.get_root_nodes().values_list('name', flat=True)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n'), name='set_language'),
    path("", RedirectView.as_view(pattern_name='document:exercises-list-no-filter', permanent=False)),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html",
                                       extra_context=dict(list_parent_ontology=root_ontology())), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("users/", include("exoset.users.urls", namespace="users")),
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("resources/", include("exoset.document.urls", namespace="document")),
    path("admin_github/", decorator_include([login_required, only_user('github_user')],
         include("exoset.githubadmin.urls", namespace="githubadmin"))),
    path("graphapi/", include("exoset.graphapi.urls", namespace="graphapi")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += django_tequila_urlpatterns

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

exoset/document/urls.py
from django.urls import include, path
from .views import ResourceDetailView, getTagConcept, get_files, ExercisesList, overleaf_link, overleaf_link_series, \
    CartAPI, download_series, download_pdf
    #, ResourceList, ResourceListing, getAuthors, getLevel, getTagFamily, getCourse, getLanguage, getOntology

app_name = "document"

urlpatterns = [

    path('<slug:slug>', ResourceDetailView.as_view(), name='resource-detail'),
    path("ajax/tagconcept/", getTagConcept, name='autocomplete'),
    path("download/<int:obj_pk>", get_files, name='get_files'),
    path("overleaf/<slug:slug>", overleaf_link, name='overleaf_exercise'),
    path("overleaf_series/<str:id_list>", overleaf_link_series, name='overleaf_series'),
    path("download_series/<str:id_list>", download_series, name='download_series'),
    path("download_pdf/<str:id_list>", download_pdf, name='download_pdf'),
    path('<str:ontologyRoot>/', ExercisesList.as_view(), name='exercises-list'),
    path('', ExercisesList.as_view(), name='exercises-list-no-filter'),
    path('<str:ontologyRoot>/<str:ontologyParent>/', ExercisesList.as_view(),
         name='exercises-list-parentOntology'),
    path('<str:ontologyRoot>/<str:ontologyParent>/<str:ontologyChild>', ExercisesList.as_view(),
         name='exercises-list-childOntology'),
    path("1/cart", CartAPI.as_view(), name='cart'),
    # Your stuff: custom urls includes go here
]

exoset/graphapi/urls.py
from django.urls import include, path
from .views import ListExercises
app_name = "graphapi"

urlpatterns = [
    path('', ListExercises.as_view(), name='graph_api'),
    ]

exoset/users/urls.py
from django.urls import path

from exoset.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

exoset/accademic/models.py
from django.db import models
from exoset.document.models import Resource
# Create your models here.


class Sector(models.Model):
    """
    identify a category of disciplinary field (biology, engineering, science of life..)
    """
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)


class Course(models.Model):
    """
    class for storing all information about a class
    """
    EPFL = "EPFL"
    INSTITUTE_CHOICES = (
        (EPFL, 'EPFL'),
    )
    I = "I"
    II = "II"
    III = "III"
    IV = "IV"
    SEMESTER_CHOICES = (
        (I, 'I'),
        (II, 'II'),
        (III, 'III'),
        (IV, 'IV'),
    )
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    institute = models.CharField(max_length=4, choices=INSTITUTE_CHOICES, default=EPFL)
    semester = models.CharField(max_length=4, choices=SEMESTER_CHOICES, default=I)
    resource = models.ManyToManyField(Resource, blank=True)

    def __str__(self):
        return self.sector.name + self.semester

exoset/graphapi/models.py
from django.db import models

# Create your models here.

exoset/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

exoset/document/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect, Http404
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe
from django.db.models import Q
from django.utils.translation import override
from django.views.generic import DetailView, ListView
from .models import Resource, Document, LANGUAGES_CHOICES, ResourceSourceFile
from exoset.tag.models import TagConcept, TagLevelResource, TagLevel
from exoset.accademic.models import Course, Sector
from exoset.ontology.models import DocumentCategory, Ontology
from datetime import datetime
import os, re
import zipfile
from io import BytesIO
import logging
import urllib.parse
from unidecode import unidecode
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
import shutil

logger = logging.getLogger(__name__)


def user_is_teacher(user):
    teacher = False
    if 'teacher' in user.groups.values_list('name', flat=True):
        teacher = True
    return teacher


def teacher_functionality(func):
    # This decorator determines if the user has the right on the specific github repository
    @login_required()
    def wrapped(self, *args, **kwargs):
        #if self.user.groups.filter(name='teacher'):
        if user_is_teacher(self.user):
            return func(self, *args, **kwargs)
        else:
            #return HttpResponse('Unauthorized', status=401)
            raise PermissionDenied
    return wrapped


# Create your views here.
def get_files(request, obj_pk):
    # Files (local path) to put in the .zip
    # FIXME: Change this (get paths from DB etc)
    try:
        resource_source_files_obj = ResourceSourceFile.objects.get(resource_id=obj_pk)
    except ResourceSourceFile.DoesNotExist:
        msg = _("Sorry, there was a problem with the file, please contact us")
        resp = HttpResponse(msg, content_type='text/plain')
        return resp
    path = resource_source_files_obj.source
    path_style = resource_source_files_obj.style
    print('resource style path is : ' + str(path_style))
    # Folder name in ZIP archive which contains the above files
    # E.g [thearchive.zip]/somefiles/file2.txt
    # FIXME: Set this to something better
    zip_subdir = "exercise"
    zip_filename = "%s.zip" % zip_subdir
    # Open StringIO to grab in-memory ZIP contents
    s = BytesIO()
    # The zip compressor
    zf = zipfile.ZipFile(s, "w")
    for root, dirs, files in os.walk(path):
        for file in files:
            zf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), os.path.join(path, '..')))
    for root, dirs, files in os.walk(path_style):
        for file in files:
            zf.write(os.path.join(root, file), os.path.relpath(os.path.join(root, file), os.path.join(path_style, '..')))
    zf.close()
    user = request.user
    if 'teacher' in user.groups.values_list('name', flat=True):
        resp = HttpResponse(s.getvalue(), content_type="application/x-zip-compressed")
        resp['Content-Disposition'] = 'attachment; filename=%s' % zip_filename
    else:
        msg = _("You have no rights to download this file")
        resp = HttpResponse(msg, content_type='text/plain')
    return resp


def getTagConcept(request):
    if request.is_ajax():
        q = request.GET.get('term', '').capitalize()
        search_qs = list(TagConcept.objects.filter(label__icontains=q).values('label').distinct())
        concepts_list = [i for i in search_qs]
        data = {
            'tagsconcepts': concepts_list,
        }
        return JsonResponse(data, status=200, safe=False)

import tempfile
def create_zip(zip_object, path, path_style):
    for (root, dirs, filenames) in os.walk(path):
        for file in filenames:
            if file.endswith('.tex') or file.endswith('_t'):

                modified = False
                with open(os.path.join(root, file)) as fid:
                    lines = fid.readlines()
                    for line_idx in range(len(lines)):
                        line = lines[line_idx]
                        match = re.match(r'(.*\\includegraphics\*?(?:\[[^\]]*\])*\{)([^{}]*)(}.*)', line)
                        match_latex_figure = re.match(r'(.*\\input{)([^}]*)(}.*)', line)
                        if match is not None:
                            modified = True
                            start, figure_path, end = match.groups()
                            figure_path = os.path.join(path.rsplit('/', 1)[1], figure_path)
                            lines[line_idx] = start + figure_path + end + '\n'
                        if match_latex_figure is not None:
                            modified = True
                            start_latex, figure_path_latex, end_latex = match_latex_figure.groups()
                            figure_path_latex = os.path.join(path.rsplit('/', 1)[1], figure_path_latex)
                            lines[line_idx] = start_latex + figure_path_latex + end_latex
                    if modified:
                        tmp = tempfile.NamedTemporaryFile()
                        with open(tmp.name, 'w') as tmp_file:
                            for new_line in lines:
                                tmp_file.write(new_line)
                        zip_object.write(tmp.name,
                                         os.path.relpath(os.path.join(root, file), os.path.join(path, '..')))
                        continue
            zip_object.write(os.path.join(root, file),
                             os.path.relpath(os.path.join(root, file), os.path.join(path, '..')))
    for (root, dirs, filenames) in os.walk(path_style):
        for file in filenames:
            zip_object.write(os.path.join(root, file),
                             os.path.relpath(os.path.join(root, file), os.path.join(path_style, '..')))
    return zip_object


@teacher_functionality
def overleaf_link(request, slug):
    from zipfile import ZipFile
    result = ""
    resurcesourcefile_obj = ResourceSourceFile.objects.get(resource__slug=slug)
    path = resurcesourcefile_obj.source
    path_style = resurcesourcefile_obj.style
    if not os.path.exists(settings.MEDIA_ROOT + '/overleaf'):
        os.makedirs(settings.MEDIA_ROOT + '/overleaf')
    path_tmp = settings.MEDIA_ROOT + '/overleaf/' + resurcesourcefile_obj.resource.slug + '.zip'
    #TODO add cartouche with folder
    if os.path.exists(path_tmp):
        result = path_tmp
    else:
        zip_object = ZipFile(path_tmp, 'w')
        create_zip(zip_object, path, path_style)
        zip_object.close()
        result = path_tmp
    overleaf_url = 'https://www.overleaf.com/docs?snip_uri[]=' + settings.DOMAIN_NAME + settings.MEDIA_URL + \
                   result.split(settings.MEDIA_URL)[1]
    return HttpResponseRedirect(overleaf_url)


def build_zip_series(id_list):
    result = ""
    id_list = id_list.split(',')
    series_name = str(datetime.now().timestamp())
    if not os.path.exists(settings.MEDIA_ROOT + '/overleaf'):
         os.makedirs(settings.MEDIA_ROOT + '/overleaf')
    path_tmp = settings.MEDIA_ROOT + '/overleaf/' + series_name + '.zip'
    path_style = settings.MEDIA_ROOT + '/overleaf/cartouche'

    initial_common_text = "\documentclass[12pt,dvipsnames]{article}\n"
    preamble = 'preamble'
    solution_common_text = '\\begin{center}\n \\vspace*{5mm} \n \\noindent \end{center}\n '
    end_document = '\n\input{cartouche/generic/cartouche}\n \end{document}\n'
    statement_text = ''
    solution_text = ''
    with zipfile.ZipFile(path_tmp, 'w') as zip_object:
        i = 1
        for id in id_list:
            try:
                resurcesourcefile_obj = ResourceSourceFile.objects.get(resource__id=int(id))
                path = resurcesourcefile_obj.source
                language_resource = resurcesourcefile_obj.resource.language
                title_resource = resurcesourcefile_obj.resource.title
                if language_resource == 'ENGLISH':
                    section_paragraph = '\section{Exercise '
                    end_document = '\n\input{cartouche/generic/cartouche_en}\n \end{document}\n'
                    subsection_statement_paragraph = '\n\subsection{Statement}\n'
                    subsection_solution_paragraph = '\n\subsection{Solution}\n'
                    preamble = 'preamble_en'
                else:
                    section_paragraph = '\section{Exercice '
                    subsection_statement_paragraph = '\n\subsection{Énoncé}\n'
                    subsection_solution_paragraph = '\n\subsection{Solution}\n'
                statement_text += section_paragraph + str(
                    i) + ' - ' + title_resource + '}\n' + subsection_statement_paragraph + '\input{' + path.rsplit('/')[
                                      -1] + '/' + path.rsplit('/')[-1] + '_E}\n'
                solution_text += section_paragraph + str(
                    i) + ' - ' + title_resource + '}\n' + subsection_statement_paragraph + '\input{' + path.rsplit('/')[
                                     -1] + '/' + path.rsplit('/')[
                                     -1] + '_E}\n' + subsection_solution_paragraph + '\input{' + path.rsplit('/')[
                                     -1] + '/' + path.rsplit('/')[-1] + '_S}\n'
                i += 1
            except ResourceSourceFile.DoesNotExist:
                continue
            create_zip(zip_object, path, path_style)
        # create compile file for statements
        initial_common_text_after_language = "\input{cartouche/generic/" + preamble + "}\n\n" \
                                            "\\begin{document}\n \\tableofcontents\n\\newpage\n\\begin{center}\n \\vspace*{10mm}\n \\noindent {\Large {\\bf Series}} \n " \
                                            "\end{center}\n "
        statement_common_text = initial_common_text + initial_common_text_after_language + statement_text

exoset/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

exoset/templates/base.html
{% extends "index.html" %}
{% load static i18n %}

exoset/templates/base_template.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ExoSet</title>
  <script src="https://cdn.polyfill.io/v2/polyfill.js?features=String.prototype.includes,Array.prototype.includes,Array.prototype.find,CustomEvent"></script>

  <!-- Matomo -->
  <script>
    var _paq = window._paq = window._paq || [];
    /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
      var u="//cedelogger.epfl.ch/";
      _paq.push(['setTrackerUrl', u+'matomo.php']);
      _paq.push(['setSiteId', '2']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
    })();
  </script>
<!-- End Matomo Code -->
  <!-- Jquery library -->
  <script src="{% static 'js/jquery_3.7.1.min.js' %}"></script>
  <!-- Favicons -->
  <link rel="icon" type="image/png" sizes="228x228" href="{% static '/images/favicons/favicon-228.png' %}">
  <link rel="icon" type="image/png" sizes="180x180" href="{% static '/images/favicons/favicon-180.png' %}">
  <link rel="icon" type="image/png" sizes="152x152" href="{% static '/images/favicons/favicon-152.png' %}">
  <link rel="icon" type="image/png" sizes="144x144" href="{% static '/images/favicons/favicon-144.png' %}">
  <link rel="icon" type="image/png" sizes="128x128" href="{% static '/images/favicons/favicon-128.png' %}">
  <link rel="icon" type="image/png" sizes="120x120" href="{% static '/images/favicons/favicon-120.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static '/images/favicons/favicons/favicon-96.png' %}">
  <link rel="icon" type="image/png" sizes="76x76" href="{% static '/images/favicons/favicon-76.png' %}">
  <link rel="icon" type="image/png" sizes="57x57" href="{% static '/images/favicons/favicon-57.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static '/images/favicons/favicons/favicon-32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static '/images/favicons/favicon-16.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static '/images/favicons/apple-touch-icon.png' %}">
  <link rel="manifest" href="{% static '/images/favicons/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static '/images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#e30713">
  <!-- end favicons -->

  <link rel="stylesheet" href="{% static 'css/vendors.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/elements.css' %}">
  <link rel="stylesheet" href="{% static 'css/reader.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">





  <script src="{% static 'js/vendors.min.js' %}"></script>
  <script src="{% static 'js/elements.js' %}"></script>
  <script src="{% static 'js/reader.js' %}"></script>
   <script src="{% static 'js/project.js' %}"></script>
  <style>

    .gray-color{
      color: #adb5bd;
    }

    .language_button{
      font-weight: bold;
      border: none;
      min-width: 45px !important;
      min-height: 50px !important;
      background: none;
      transition: text-decoration-color 0.2s ease-in-out, color 0.2s ease-in-out, -webkit-text-decoration-color 0.2s ease-in-out;
    }
    .language_button:hover{
      color: #0a0c0d;
      transition: 0.7s;
    }
    .tableExercises{
      padding: 0 30px 10px 0;

    }
    .tableExercises:after{
      content: none!important;
    }
    .tableExercisesText{
      color: #212121;
      font-size: 17px;
    }
    .list-unstyled a:before{
      background: none !important;
    }
    .nav-aside a{
      padding: 0.3rem 3rem;
    }
    ul.list-unstyled li div{
      padding: 0.3rem 3rem;
    }
    #nav-aside  form  ul{
      padding-left: 0;
    }
    #nav-aside form ul li div{
      padding-left: 4.5rem;
    }
    .title_filters{
      padding-left: 3rem !important;
      color: #ff0000;
      font-weight: bold;
      font-size: large;
    }
    .list-unstyled{
      padding-bottom: 15px;
    }
    .links_footer{
      text-decoration: none
    }
    .centered-block img{
      display: block;
      margin-left: auto;
      margin-right: auto;
    }
    .center-block {
      text-align: center;
    }
    .mobile-menu-open .header{
      overflow: visible;
    }
    .nav-lang-short ul li + li::before{
      top:1.1rem;
    }
    .breadcrumb-item:not(.breadcrumb-tags-wrapper){
      display: inline-block;
    }
    .oval{
      height: 25px;
      width: 32px;
      background-color: #ff0000;
      border-radius: 42%;
      color: #FFFFFF;
      display: inline-block;
}

  </style>
</head>
<body data-spy="scroll" data-target="#intermediate-nav" data-offset="0">

{% block content %}
{% endblock %}


</body>
</html>

exoset/templates/index.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
    <title>Exoset</title>
    {% endblock %}
    <!-- Custom fonts for this template-->
  <script src="https://cdn.polyfill.io/v2/polyfill.js?features=String.prototype.includes,Array.prototype.includes,Array.prototype.find,CustomEvent"></script>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="//apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">

  <script src="//apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="//apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>


 <!-- <link rel="stylesheet" href="jqueryui/style.css" type="text/css">-->

<!-- Favicons -->
  <link rel="icon" type="image/png" sizes="228x228" href="{% static '/images/favicons/favicon-228.png' %}">
  <link rel="icon" type="image/png" sizes="180x180" href="{% static '/images/favicons/favicon-180.png' %}">
  <link rel="icon" type="image/png" sizes="152x152" href="{% static '/images/favicons/favicon-152.png' %}">
  <link rel="icon" type="image/png" sizes="144x144" href="{% static '/images/favicons/favicon-144.png' %}">
  <link rel="icon" type="image/png" sizes="128x128" href="{% static '/images/favicons/favicon-128.png' %}">
  <link rel="icon" type="image/png" sizes="120x120" href="{% static '/images/favicons/favicon-120.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static '/images/favicons/favicons/favicon-96.png' %}">
  <link rel="icon" type="image/png" sizes="76x76" href="{% static '/images/favicons/favicon-76.png' %}">
  <link rel="icon" type="image/png" sizes="57x57" href="{% static '/images/favicons/favicon-57.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static '/images/favicons/favicons/favicon-32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static '/images/favicons/favicon-16.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static '/images/favicons/apple-touch-icon.png' %}">
  <link rel="manifest" href="{% static '/images/favicons/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static '/images/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="theme-color" content="#e30713">
  <!-- end favicons -->


<link rel="stylesheet" href="{% static 'css/vendors.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/elements.css' %}">
  <link rel="stylesheet" href="{% static 'css/reader.css' %}">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>

    .gray-color{
      color: #adb5bd;
    }

    .language_button{
      font-weight: bold;
      border: none;
      min-width: 45px !important;
      min-height: 50px !important;
      background: none;
      transition: text-decoration-color 0.2s ease-in-out, color 0.2s ease-in-out, -webkit-text-decoration-color 0.2s ease-in-out;
    }
    .language_button:hover{
      color: #0a0c0d;
      transition: 0.7s;
    }
    .tableExercises{
      padding: 0 30px 10px 0;

    }
    .tableExercises:after{
      content: none!important;
    }
    .tableExercisesText{
      color: #212121;
      font-size: 17px;
    }
    .list-unstyled a:before{
      background: none !important;
    }
    .nav-aside a{
      padding: 0.3rem 3rem;
    }
    ul.list-unstyled li div{
      padding: 0.3rem 3rem;
    }
    #nav-aside  form  ul{
      padding-left: 0;
    }
    #nav-aside form ul li div{
      padding-left: 4.5rem;
    }
    .title_filters{
      padding-left: 3rem !important;
      color: #ff0000;
      font-weight: bold;
      font-size: large;
    }
    .list-unstyled{
      padding-bottom: 15px;
    }
    .links_footer{
      text-decoration: none
    }
    .centered-block img{
      display: block;
      margin-left: auto;
      margin-right: auto;
    }
    .center-block {
      text-align: center;
    }
    .mobile-menu-open .header{
      overflow: visible;
    }
    .nav-lang-short ul li + li::before{
      top:1.1rem;
    }
    .breadcrumb-item:not(.breadcrumb-tags-wrapper){
      display: inline-block;
    }
  </style>

</head>

<body id="page-top">



    <!-- Bootstrap core JavaScript-->
    <!--<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>-->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}" type="text/javascript"></script>
    <!--<script src="{% static 'js/project.js' %}" type="text/javascript"></script>-->
    <!-- Page level plugins -->



<script>
  $(function() {
    $("#concept_autocomplete").autocomplete({
      source: "{% url 'document:autocomplete' %}",
      minLength: 2,
    });
  });
</script>
{% block content %}
{% endblock %}
</body>

</html>